import { TableState } from "@/stores/TableStore";

export const templates: Record<string, Omit<TableState, "datasource">> = {
  blank: {
    models: [],
    enums: [],
    positions: {},
  },
  blog_basic: {
    models: [
      {
        name: "User",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "posts",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            relationName: "PostToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "profile",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Profile",
            relationName: "ProfileToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Profile",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "user",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "ProfileToUser",
            relationFromFields: ["userId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "userId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Post",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "PostToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "categories",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Category",
            relationName: "CategoryToPost",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Category",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "posts",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            relationName: "CategoryToPost",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
    ],
    enums: [],
    positions: {
      Post: {
        x: 364.96931197954916,
        y: -1.110997171433155,
      },
      Category: {
        x: 294.44881217026915,
        y: 339.59013653408795,
      },
      User: {
        x: -139.41473601523515,
        y: 365.9613199261149,
      },
      Profile4: null,
      Profile: {
        x: -261,
        y: 72,
      },
      Profile44: null,
      Profile444d: null,
      Profile444: {
        x: -154.52489759025747,
        y: 22.26347942483173,
      },
      Enum: {
        x: 683.8728103959793,
        y: 84.03521822662458,
      },
    },
  },
  blog_advanced: {
    models: [
      {
        name: "User",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "email",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "posts",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            relationName: "PostToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "comments",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            relationName: "CommentToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Post",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "title",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "content",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "published",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Boolean",
            default: false,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "PostToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "comments",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            relationName: "CommentToPost",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "categories",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Category",
            relationName: "CategoryToPost",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "tags",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Tag",
            relationName: "PostToTag",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Comment",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "content",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "post",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            relationName: "CommentToPost",
            relationFromFields: ["postId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "postId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "CommentToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Category",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "posts",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            relationName: "CategoryToPost",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Tag",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "posts",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            relationName: "PostToTag",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
    ],
    enums: [],
    positions: {
      Post: {
        x: 39.86643132111311,
        y: -162.97656644440988,
      },
      Category: {
        x: 678.536603665468,
        y: 399.9467894833334,
      },
      User: {
        x: -139.41473601523515,
        y: 365.9613199261149,
      },
      Profile4: null,
      Profile: {
        x: -261,
        y: 72,
      },
      Profile44: null,
      Profile444d: null,
      Profile444: {
        x: -154.52489759025747,
        y: 22.26347942483173,
      },
      Enum: {
        x: 683.8728103959793,
        y: 84.03521822662458,
      },
      Tag: {
        x: -355.2112482853223,
        y: -93.11111111111109,
      },
      Comment: {
        x: -725.6515775034293,
        y: 204.3895747599451,
      },
    },
  },
  ecommerce_basic: {
    models: [
      {
        name: "User",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "email",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "password",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "orders",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Order",
            relationName: "OrderToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Product",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "description",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "price",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Float",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "quantity",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: 0,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "categories",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Category",
            relationName: "CategoryToProduct",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "orderItems",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "OrderItem",
            relationName: "OrderItemToProduct",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Category",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "products",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Product",
            relationName: "CategoryToProduct",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Order",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "totalAmount",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Float",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "status",
            kind: "enum",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "OrderStatus",
            default: "PENDING",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "user",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "OrderToUser",
            relationFromFields: ["userId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "userId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "items",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "OrderItem",
            relationName: "OrderToOrderItem",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "OrderItem",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "quantity",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "product",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Product",
            relationName: "OrderItemToProduct",
            relationFromFields: ["productId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "productId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "order",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Order",
            relationName: "OrderToOrderItem",
            relationFromFields: ["orderId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "orderId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "price",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Float",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
    ],
    enums: [
      {
        name: "OrderStatus",
        values: [
          {
            name: "PENDING",
            dbName: null,
          },
          {
            name: "SHIPPED",
            dbName: null,
          },
          {
            name: "DELIVERED",
            dbName: null,
          },
          {
            name: "CANCELLED",
            dbName: null,
          },
        ],
        dbName: null,
      },
    ],
    positions: {
      Post: {
        x: 39.86643132111311,
        y: -162.97656644440988,
      },
      Category: {
        x: 133.83964860390563,
        y: 71.13768772153645,
      },
      User: {
        x: -995.6079358981473,
        y: 31.164017487321274,
      },
      Profile4: null,
      Profile: {
        x: -261,
        y: 72,
      },
      Profile44: null,
      Profile444d: null,
      Profile444: {
        x: -154.52489759025747,
        y: 22.26347942483173,
      },
      Enum: {
        x: 683.8728103959793,
        y: 84.03521822662458,
      },
      Tag: {
        x: -355.2112482853223,
        y: -93.11111111111109,
      },
      Comment: {
        x: -725.6515775034293,
        y: 204.3895747599451,
      },
      PaymentType: {
        x: 340.57628683996177,
        y: 36.8434442229734,
      },
      OrderStatus: {
        x: -98.32115641441999,
        y: -232.54587395897758,
      },
      CartItem: {
        x: -1241.8072288553312,
        y: 392.74453100114687,
      },
      Cart: {
        x: -1210.355848045929,
        y: 1.3935256794066664,
      },
      PaymentMethod: {
        x: 5.403953578940673,
        y: -95.98857106985841,
      },
      OrderItem: {
        x: -815.0353488756181,
        y: 341.40652556804037,
      },
      Order: {
        x: -448.1036446171894,
        y: -148.48440918180987,
      },
      Product: {
        x: -343.1321807127065,
        y: 251.66347344516578,
      },
    },
  },
  ecommerce_advanced: {
    models: [
      {
        name: "User",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "email",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "password",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "orders",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Order",
            relationName: "OrderToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "cart",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Cart",
            relationName: "CartToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Product",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "description",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "price",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Float",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "quantity",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: 0,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "categories",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Category",
            relationName: "CategoryToProduct",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "orders",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "OrderItem",
            relationName: "OrderItemToProduct",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "cartItems",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "CartItem",
            relationName: "CartItemToProduct",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Category",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "products",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Product",
            relationName: "CategoryToProduct",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Order",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "totalAmount",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Float",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "status",
            kind: "enum",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "OrderStatus",
            default: "PENDING",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "user",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "OrderToUser",
            relationFromFields: ["userId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "userId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "items",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "OrderItem",
            relationName: "OrderToOrderItem",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "payment",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "PaymentMethod",
            relationName: "OrderToPaymentMethod",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "OrderItem",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "quantity",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "product",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Product",
            relationName: "OrderItemToProduct",
            relationFromFields: ["productId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "productId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "order",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Order",
            relationName: "OrderToOrderItem",
            relationFromFields: ["orderId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "orderId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "price",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Float",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "PaymentMethod",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "type",
            kind: "enum",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "PaymentType",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "order",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Order",
            relationName: "OrderToPaymentMethod",
            relationFromFields: ["orderId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "orderId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Cart",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "user",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "CartToUser",
            relationFromFields: ["userId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "userId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "items",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "CartItem",
            relationName: "CartToCartItem",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "CartItem",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "product",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Product",
            relationName: "CartItemToProduct",
            relationFromFields: ["productId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "productId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "quantity",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "cart",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Cart",
            relationName: "CartToCartItem",
            relationFromFields: ["cartId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "cartId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
    ],
    enums: [
      {
        name: "OrderStatus",
        values: [
          {
            name: "PENDING",
            dbName: null,
          },
          {
            name: "COMPLETED",
            dbName: null,
          },
          {
            name: "CANCELLED",
            dbName: null,
          },
        ],
        dbName: null,
      },
      {
        name: "PaymentType",
        values: [
          {
            name: "CREDIT_CARD",
            dbName: null,
          },
          {
            name: "PAYPAL",
            dbName: null,
          },
          {
            name: "STRIPE",
            dbName: null,
          },
        ],
        dbName: null,
      },
    ],
    positions: {
      Post: {
        x: 39.86643132111311,
        y: -162.97656644440988,
      },
      Category: {
        x: -35.23278553042849,
        y: 476.2070611683787,
      },
      User: {
        x: -851.1918984084036,
        y: 11.204077346462384,
      },
      Profile4: null,
      Profile: {
        x: -261,
        y: 72,
      },
      Profile44: null,
      Profile444d: null,
      Profile444: {
        x: -154.52489759025747,
        y: 22.26347942483173,
      },
      Enum: {
        x: 683.8728103959793,
        y: 84.03521822662458,
      },
      Tag: {
        x: -355.2112482853223,
        y: -93.11111111111109,
      },
      Comment: {
        x: -725.6515775034293,
        y: 204.3895747599451,
      },
      PaymentType: {
        x: 340.57628683996177,
        y: 36.8434442229734,
      },
      OrderStatus: {
        x: -1028.2195441532576,
        y: -298.2962650112186,
      },
      CartItem: {
        x: -1241.8072288553312,
        y: 392.74453100114687,
      },
      Cart: {
        x: -1210.355848045929,
        y: 1.3935256794066664,
      },
      PaymentMethod: {
        x: 5.403953578940673,
        y: -95.98857106985841,
      },
      OrderItem: {
        x: 171.2205169079976,
        y: 223.99511297475277,
      },
      Order: {
        x: -614.8278504996576,
        y: -180.1854905819975,
      },
      Product: {
        x: -589.6961471586103,
        y: 256.3599299488973,
      },
    },
  },
  task: {
    models: [
      {
        name: "User",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "email",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "password",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "tasks",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Task",
            relationName: "TaskToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "projects",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Project",
            relationName: "ProjectToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "comments",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            relationName: "CommentToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Project",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "description",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "owner",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "ProjectToUser",
            relationFromFields: ["ownerId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "ownerId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "tasks",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Task",
            relationName: "ProjectToTask",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Task",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "title",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "description",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "status",
            kind: "enum",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "TaskStatus",
            default: "PENDING",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "priority",
            kind: "enum",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "TaskPriority",
            default: "MEDIUM",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "dueDate",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "assignedTo",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "TaskToUser",
            relationFromFields: ["assignedToId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "assignedToId",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "project",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Project",
            relationName: "ProjectToTask",
            relationFromFields: ["projectId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "projectId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "comments",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            relationName: "CommentToTask",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Comment",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "content",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "CommentToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "task",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Task",
            relationName: "CommentToTask",
            relationFromFields: ["taskId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "taskId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
    ],
    enums: [
      {
        name: "TaskStatus",
        values: [
          {
            name: "PENDING",
            dbName: null,
          },
          {
            name: "IN_PROGRESS",
            dbName: null,
          },
          {
            name: "COMPLETED",
            dbName: null,
          },
          {
            name: "BLOCKED",
            dbName: null,
          },
        ],
        dbName: null,
      },
      {
        name: "TaskPriority",
        values: [
          {
            name: "LOW",
            dbName: null,
          },
          {
            name: "MEDIUM",
            dbName: null,
          },
          {
            name: "HIGH",
            dbName: null,
          },
        ],
        dbName: null,
      },
    ],
    positions: {
      Post: {
        x: 39.86643132111311,
        y: -162.97656644440988,
      },
      Category: {
        x: 133.83964860390563,
        y: 71.13768772153645,
      },
      User: {
        x: -1037.0363370806808,
        y: -92.05891936329103,
      },
      Profile4: null,
      Profile: {
        x: -261,
        y: 72,
      },
      Profile44: null,
      Profile444d: null,
      Profile444: {
        x: -154.52489759025747,
        y: 22.26347942483173,
      },
      Enum: {
        x: 683.8728103959793,
        y: 84.03521822662458,
      },
      Tag: {
        x: -355.2112482853223,
        y: -93.11111111111109,
      },
      Comment: {
        x: -1215.356524814914,
        y: 326.5502449135694,
      },
      PaymentType: {
        x: 340.57628683996177,
        y: 36.8434442229734,
      },
      OrderStatus: {
        x: -98.32115641441999,
        y: -232.54587395897758,
      },
      CartItem: {
        x: -1241.8072288553312,
        y: 392.74453100114687,
      },
      Cart: {
        x: -1210.355848045929,
        y: 1.3935256794066664,
      },
      PaymentMethod: {
        x: 5.403953578940673,
        y: -95.98857106985841,
      },
      OrderItem: {
        x: -815.0353488756181,
        y: 341.40652556804037,
      },
      Order: {
        x: -448.1036446171894,
        y: -148.48440918180987,
      },
      Product: {
        x: -343.1321807127065,
        y: 251.66347344516578,
      },
      TaskPriority: {
        x: 67.68063820556293,
        y: 21.850145107026165,
      },
      TaskStatus: {
        x: 74.59196320647735,
        y: 249.91825176236733,
      },
      Task: {
        x: -328.2404093693033,
        y: -93.47946933494725,
      },
      Project: {
        x: -865.7473580452497,
        y: 387.72734440063334,
      },
    },
  },
  QnA: {
    models: [
      {
        name: "User",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "username",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "email",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "password",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "questions",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Question",
            relationName: "QuestionToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "answers",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Answer",
            relationName: "AnswerToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Question",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "title",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "content",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "QuestionToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "answers",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Answer",
            relationName: "AnswerToQuestion",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "tags",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Tag",
            relationName: "QuestionToTag",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Answer",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "content",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            relationName: "AnswerToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "question",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Question",
            relationName: "AnswerToQuestion",
            relationFromFields: ["questionId"],
            relationToFields: ["id"],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "questionId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            default: {
              name: "now",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Tag",
        dbName: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            default: {
              name: "autoincrement",
              args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "questions",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Question",
            relationName: "QuestionToTag",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
    ],
    enums: [],
    positions: {
      Post: {
        x: 39.86643132111311,
        y: -162.97656644440988,
      },
      Category: {
        x: 133.83964860390563,
        y: 71.13768772153645,
      },
      User: {
        x: -799.0363370806808,
        y: -133.058919363291,
      },
      Profile4: null,
      Profile: {
        x: -261,
        y: 72,
      },
      Profile44: null,
      Profile444d: null,
      Profile444: {
        x: -154.52489759025747,
        y: 22.26347942483173,
      },
      Enum: {
        x: 683.8728103959793,
        y: 84.03521822662458,
      },
      Tag: {
        x: -475.2112482853223,
        y: 351.8888888888889,
      },
      Comment: {
        x: -1215.356524814914,
        y: 326.5502449135694,
      },
      PaymentType: {
        x: 340.57628683996177,
        y: 36.8434442229734,
      },
      OrderStatus: {
        x: -98.32115641441999,
        y: -232.54587395897758,
      },
      CartItem: {
        x: -1241.8072288553312,
        y: 392.74453100114687,
      },
      Cart: {
        x: -1210.355848045929,
        y: 1.3935256794066664,
      },
      PaymentMethod: {
        x: 5.403953578940673,
        y: -95.98857106985841,
      },
      OrderItem: {
        x: -815.0353488756181,
        y: 341.40652556804037,
      },
      Order: {
        x: -448.1036446171894,
        y: -148.48440918180987,
      },
      Product: {
        x: -343.1321807127065,
        y: 251.66347344516578,
      },
      TaskPriority: {
        x: 67.68063820556293,
        y: 21.850145107026165,
      },
      TaskStatus: {
        x: 74.59196320647735,
        y: 249.91825176236733,
      },
      Task: {
        x: -328.2404093693033,
        y: -93.47946933494725,
      },
      Project: {
        x: -865.7473580452497,
        y: 387.72734440063334,
      },
      Answer: {
        x: -772,
        y: 259,
      },
      Question: {
        x: -108,
        y: -170,
      },
    },
  },
};
